problems: ["CA", "SC", "IS", "CFL"]
is_sizes: [10, 50, 200]
ca_sizes: [5, 25, 100]
sc_sizes: [10, 50, 200]
cfl_sizes: [10, 50, 200]
rnd_sizes: [10, 50, 200]
data_root: ./data/instances/milp

num_blocks: 5
halo_hops: 0
