# Docker Compose configuration for KKT_MPNN with conda environment
services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      # Mount source code for development (optional - uncomment if needed)
      # - ./:/app
      # Mount for conda package cache
      - conda-pkg-cache:/opt/conda/pkgs
    # If you need GPU support for PyTorch, uncomment these lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0 # Only use first GPU if multiple are available
      - PYTHONFAULTHANDLER=1 # Help debug crashes

volumes:
  conda-pkg-cache: # Persistent volume for conda package cache to speed up subsequent builds
