data:
  problems: ["CA"]
  is_sizes: [2]
  ca_sizes: [50]
  sc_sizes: [2]
  cfl_sizes: [5]
  rnd_sizes: [10]
  data_root: ./data/instances

mlp:
  hidden: 256
  embed_dim: 128
  lejepa_local_mask: [0.40, 0.20, 0.20] # Local views masking ratios
gnn:
  embedding_size: 256
  cons_nfeats: 4
  edge_nfeats: 1
  var_nfeats: 18
  num_emb_type: periodic
  num_emb_bins: 32
  num_emb_freqs: 16
  lejepa_local_mask: 0.4
  lejepa_global_mask: 0.95
  bipartite_conv: gatv2
  attn_heads: 8
  dropout: 0.05

training:
  use_bipartite_graphs: true
  optimizer: adam
  weight_decay: 0.0
  scheduler: cosine_warmup
  warmup_pct: 0.05
  min_lr_ratio: 0.1
  devices: "0"
  batch_size: 128
  epochs: 4000
  lr: 0.001
  seed: 42
  log_every: 10
  wandb_project: kkt_gnn_pretraining
  experiments_dir: ./experiments
  lejepa_lambda_start: 0.40
  lejepa_lambda_warm_epochs: 20
  primal_weight: 0.1
  dual_weight: 0.1
  stationarity_weight: 0.6
  complementary_slackness_weight: 0.2
