# sweep.yaml
method: random
metric:
  name: valid/lejepa_loss
  goal: minimize
parameters:
  epochs:
    value: 100
  early_stop_patience:
    value: 15
  early_stop_min_delta:
    value: 0.01

  lejepa_lambda:
    distribution: uniform
    min: 0.01
    max: 0.25

  lejepa_n_global_views:
    values: [1, 2, 3]
  lejepa_n_local_views:
    values: [4, 6, 8]

  lejepa_global_mask:
    values: [0.70, 0.80, 0.90, 0.95]
  lejepa_local_mask:
    values: [0.20, 0.30, 0.40, 0.50]

  sigreg_slices:
    values: [256, 512, 768]
  sigreg_points:
    values: [9, 13, 17, 21]
  dropout:
    values: [0.0, 0.1, 0.2, 0.3]

early_terminate:
  type: hyperband
  max_iter: 150
  s: 2
